# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-03 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='servicio',
            field=models.CharField(choices=[('Lavado de motor', 'Lavado de motor'), ('Hidro Lavadoras', 'Hidro Lavadoras'), ('Compresores', 'Compresores'), ('Maquinas de ejercicio', 'Maquinas de ejercicio')], default='Servicio1', max_length=9),
        ),
    ]
